# Generated by Django 5.2.8 on 2025-11-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tickettype',
            name='limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ticket.event'),
            preserve_default=False,
        ),
    ]
