# Generated by Django 5.1.1 on 2025-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
