# Generated by Django 5.1.1 on 2025-11-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
