# Generated by Django 5.2.8 on 2025-11-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
    ]
