# Generated by Django 5.2.8 on 2025-11-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_sitesettings_site_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
