# Generated by Django 5.2.8 on 2025-12-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_staffuser_staffscansummary_ticketsalessummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketsalessummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticketsalessummary',
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='StaffScanSummary',
        ),
        migrations.DeleteModel(
            name='TicketSalesSummary',
        ),
    ]
