# Generated by Django 5.2.8 on 2025-12-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_staffscansummary_ticketsalessummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket Type Summary',
                'verbose_name_plural': 'Ticket Type Summaries',
            },
        ),
    ]
